# octocatalog-diff

language: ruby
install: true
script: "script/cibuild"

matrix:
  include:
    # Build with latest ruby
    - rvm: 2.5
      env: RUBOCOP_TEST="true" RSPEC_TEST="true" PUPPET_VERSIONS="5.0.0"
    # Puppet supports ruby 2.4 with Puppet >= 5.0 so this should be considered the "official" build
    - rvm: 2.4
      env: RUBOCOP_TEST="false" RSPEC_TEST="true" ENFORCE_COVERAGE="true" PUPPET_VERSIONS="5.0.0"
    # Puppet supports ruby 2.0 and 2.1 with Puppet 4.x, but build with more recent versions too
    - rvm: 2.3
      env: RUBOCOP_TEST="false" RSPEC_TEST="true" PUPPET_VERSIONS="4.10.8"
    - rvm: 2.2
      env: RUBOCOP_TEST="false" RSPEC_TEST="true" PUPPET_VERSIONS="4.10.8"
    # For really old ruby versions only build 3.8.7
    - rvm: 2.1
      env: RUBOCOP_TEST="false" RSPEC_TEST="true" PUPPET_VERSIONS="3.8.7"
    - rvm: 2.0
      env: RUBOCOP_TEST="false" RSPEC_TEST="true" PUPPET_VERSIONS="3.8.7"
